using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace UserAuth.Authorization;

public class AgeAuthorization : AuthorizationHandler<MinAge> // AuthorizationHandler by MinAge class
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, 
        MinAge requirement) // abstract class generated by AuthorizationHandler inheritance 
    {
        var dateClaim = context.User.FindFirst(x => x.Type == ClaimTypes.DateOfBirth); // context from AuthorizationHandler
        // Type == type of the claim, then, using method ClaimTypes and getting access for all claim types
        if (dateClaim == null)
        {
            return Task.CompletedTask; // task completed == end of results
        }

        var date = Convert.ToDateTime(dateClaim.Value);

        var userAge = DateTime.Today.Year - date.Year;


        // verify if in this year, person already did birth, if didnt do, year decreases one -- >
        if (date > DateTime.Today.AddYears(userAge))
        {
            userAge--;
        }

        if (userAge >= requirement.Age)
        {
            context.Succeed(requirement);
        }
        //context.Succeed(requirement); -- > testing success
        return Task.CompletedTask;
    }
}
